version: '3.3'

services:
  web:
    container_name: proyecto.web
    build: ./source
    command: python /usr/src/source/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./source/:/usr/src/source/
    ports:
      - 8000:8000
    depends_on:
      - database


  database:
    image: postgres
    container_name: proyecto.database
    restart: always
    environment:
      POSTGRES_DB: info_db
      POSTGRES_PASSWORD: d123456
      POSTGRES_USER: christian
    ports:
      - "3009:5432"
    volumes:
      - ./info_data:/var/lib/postgresql/data/

volumes:
  info_data: