version: '3.3'

services:
  web:
    container_name: table_to_shape.web
    build: ./source
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source/:/usr/src/source/
    ports:
      - 8000:8000
    depends_on:
      - database


  database:
    image: postgis/postgis
    container_name: table_to_shape.database
    restart: always
    environment:
      POSTGRES_DB: gis
      POSTGRES_PASSWORD: gis123
      POSTGRES_USER: gis
    ports:
      - "5432:5432"
    volumes:
      - ./table_to_shape_data:/var/lib/postgresql/data/

volumes:
  table_to_shape_data:



#https://video.osgeo.org/w/9cZiX3fMCtpPwhZgRw3oqa